# Generated by Django 4.1.11 on 2024-02-13 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='accountNum',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
